const Menu = [
    {
        id: 1,
        name: "Bread Omlet",
        itemLeft: 12,
        catagory: "breakfast",
        image: "../assets/images/breakfast/bread-omlet.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 2,
        name: "Croissant",
        itemLeft: 34,
        catagory: "breakfast",
        image: "../assets/images/breakfast/croissant.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 3,
        name: "Fruits",
        itemLeft: 15,
        catagory: "breakfast",
        image: "../assets/images/breakfast/fruits.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 4,
        name: "Healthy Nuts",
        itemLeft: 30,
        catagory: "breakfast",
        image: "../assets/images/breakfast/healthy-nuts.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 5,
        name: "Pan Cake",
        itemLeft: 23,
        catagory: "breakfast",
        image: "../assets/images/breakfast/pancakes.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 6,
        name: "Poori",
        itemLeft: 5,
        catagory: "breakfast",
        image: "../assets/images/breakfast/poori.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 7,
        name: "Upma",
        itemLeft: 8,
        catagory: "breakfast",
        image: "../assets/images/breakfast/upma.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 8,
        name: "Sandwich",
        itemLeft: 14,
        catagory: "breakfast",
        image: "../assets/images/breakfast/sandwich.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 9,
        name: "Aloo Paratha",
        itemLeft: 25,
        catagory: "lunch",
        image: "../assets/images/lunch/aloo-paratha.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 10,
        name: "Burger Box",
        itemLeft: 10,
        catagory: "lunch",
        image: "../assets/images/lunch/burger-box.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 11,
        name: "Chicke Biriyani",
        itemLeft: 18,
        catagory: "lunch",
        image: "../assets/images/lunch/chicken-biryani.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 12,
        name: "Healthy Sandwich",
        itemLeft: 8,
        catagory: "lunch",
        image: "../assets/images/lunch/healthy-sandwich.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 13,
        name: "Rice Box",
        itemLeft: 7,
        catagory: "lunch",
        image: "../assets/images/lunch/rice-box.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 14,
        name: "Veg Roll",
        itemLeft: 3,
        catagory: "lunch",
        image: "../assets/images/lunch/veg-rolls.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 15,
        name: "Momo",
        itemLeft: 2,
        catagory: "snacks",
        image: "../assets/images/snacks/momo.webp",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 16,
        name: "Panipuri",
        itemLeft: 60,
        catagory: "snacks",
        image: "../assets/images/snacks/panipuri.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 17,
        name: "Samosa",
        itemLeft: 2,
        catagory: "snacks",
        image: "../assets/images/snacks/samosa.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 18,
        name: "French Fries",
        itemLeft: 6,
        catagory: "snacks",
        image: "../assets/images/snacks/french-fries.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 19,
        name: "Corn Fries",
        itemLeft: 3,
        catagory: "snacks",
        image: "../assets/images/snacks/corn-fries.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 20,
        name: "Toast",
        itemLeft: 30,
        catagory: "snacks",
        image: "../assets/images/snacks/toast.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 21,
        name: "Cookies",
        itemLeft: 34,
        catagory: "snacks",
        image: "../assets/images/snacks/cookies.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 22,
        name: "Chocolate Waffle",
        itemLeft: 16,
        catagory: "snacks",
        image: "../assets/images/snacks/chocolate-waffle.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 23,
        name: "Roti Sabji",
        itemLeft: 12,
        catagory: "dinner",
        image: "../assets/images/dinner/roti-sabji.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 24,
        name: "Maxican Cheese Pizza",
        itemLeft: 8,
        catagory: "dinner",
        image: "../assets/images/dinner/maxican-cheese-pizza.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 25,
        name: "Chicken Kebab",
        itemLeft: 10,
        catagory: "dinner",
        image: "../assets/images/dinner/chicken-kebab.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 26,
        name: "Nan & Butter Chicken",
        itemLeft: 7,
        catagory: "dinner",
        image: "../assets/images/dinner/nan-chicken.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 27,
        name: "Chicken Cheese Burger",
        itemLeft: 7,
        catagory: "dinner",
        image: "../assets/images/dinner/chicken-cheese-burger.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 28,
        name: "Pasta",
        itemLeft: 7,
        catagory: "dinner",
        image: "../assets/images/dinner/pasta.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 29,
        name: "Veg Noodles",
        itemLeft: 7,
        catagory: "dinner",
        image: "../assets/images/dinner/veg-noodles.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    },
    {
        id: 30,
        name: "Subways",
        itemLeft: 7,
        catagory: "dinner",
        image: "../assets/images/dinner/subways.jpg",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error, enim doloribus? Porro qui saepe veniam!",
    }
]

export default Menu;